jazzband/django-silk

- README.md
- silk/config.py
- silk/middleware.py
I really want to integrate silk into our dev/staging environments but we need more fine-grained controls over when it is enabled. Let me know if you've been thinking of a better way to do this.
> Add configuration option for custom intercept logic.

- silk/model_factory.py
Django support inserting headers fields of type UUID. 
This pull request enabled the serialization of the UUID type when encoding the headers.
> Support UUID in request headers

- silk/model_factory.py
Resolves #89 by using Django's url_name when it is present.
A fallback is included for Django 1.6-1.7.
> Added support for missing URL names in Django 1.8-1.9.

- .travis.yml
- project/tests/test_migrations.sh
Resolves #91 by running the migration tests from a separate shell script which checks the Django verson before running ``django-admin.py syncdb`` or ``manage.py migrate``.
> Conditional migration tests

- project/test-requirements.txt
- project/tests/factories.py
- project/tests/test_filters.py
- project/tests/test_models.py
- silk/models.py
A few tests for models. I also have added new dependencies for testing.
PS Sorry for late.
> Unittests for models

- silk/model_factory.py
- silk/models.py
- silk/templates/silk/request.html
- silk/views/raw.py
removed some useless encoding/decoding of response body (why it was decoded from original charset before json dump and load??)
> Response bodies are now stored b64 encoded (support for binary responses).

- silk/templates/silk/requests.html
- silk/views/requests.py
This closes #84 
Sure, we could make it more 2.0, anyway it's a start...
> Add Ascending/Descending sort order GET parameter in RequestsView

- silk/urls.py
See the deprecation notes here: https://docs.djangoproject.com/en/1.9/ref/urls/#patterns
> URL patterns are just Python lists for Django 1.9+

- project/tests/test_config_meta.py
- silk/middleware.py
- silk/models.py
- silk/views/requests.py
- silk/views/summary.py
I can break this up, but simply this fixes:
- Django deprecation warnings.
- A previous commit broke sql and profile saving entirely.
- Stop attaching the profiler every run if not used.
- Better update of total queries (Though this really could be refactored into one update)
> Fixing Depreciation, Saving and Performance Tweaks

- requirements.txt
- setup.py
First PR here, not sure on procedures so let me know if anything else is needed. Submitting this PR to remove simplejson from requirements and setup.py. It doesn't seem to be used anywhere in the code base anymore and actually caused a failure in the requests library on our project because requests defaults to simplejson if available.
> remove simplejson

- project/example_app/views.py
- silk/views/profile_detail.py
- silk/views/profiling.py
- silk/views/raw.py
- silk/views/request_detail.py
- silk/views/requests.py
- silk/views/sql.py
- silk/views/sql_detail.py
- silk/views/summary.py
> Render function instead of render_to_response

- silk/management/commands/silk_clear_request_log.py
or else we'd get killed by OOM killer
> clear data store in chunks

- README.md
- README.rst
it's confusing to look at master's readme claiming support and then noticing
it's not supported.
> remove claim to support django 1.6

- silk/templatetags/silk_filters.py
- silk/views/sql_detail.py
by achoring based on the double quote enclosing the path instead of
using the forward slash.
> make file paths clickable that don't start with a slash

- MANIFEST.in
* Include any readme file
* See issue: https://github.com/django-silk/silk/issues/127
* The markdown README file is not included in the wheel, so systems without pyandoc cannot `pip install django-silk`
> use any readme

- silk/middleware.py
- silk/model_factory.py
multiple issues:
* resolve() might throw, handle that case
* unhandled exception in `process_request` leads to last successful
`request_model` remain in `DataCollector` and being used to create
a response model for the current failed request, leading to
a constraint violation thrown by the db (creating another response
for the previously succesful request)
resolution
* handle 404 by saving NULL/None as view name
* clean out `DataCollector` state when starting a request, before doing
anything.
> don't crash when a route is 404

- silk/collector.py
- silk/middleware.py
- silk/model_factory.py
- silk/profiling/dynamic.py
- silk/profiling/profiler.py
- silk/request_filters.py
- silk/sql.py
- silk/views/raw.py
Enables finer-grained logging configuration. If I want to suppress e.g. https://github.com/django-silk/silk/blob/6f8a5741115640dc752ef95951058b420d55dbe8/silk/profiling/profiler.py#L106 but not other warnings, with this patch I can change the logging level for `"silk.profiling.profiler" independently.
> Namespaced loggers

- silk/model_factory.py
This fixes the `test_config_max_body_size.TestMaxBodySizeResponse.test_max_response` test and suppresses an unintended warning.
> Fix ignored content body

- silk/collector.py
- silk/config.py
Hi!
This provides a new config constant to select the path in which the `prof files` should be saved (#131), It can be configured through the `SILKY_PYTHON_PROFILER_RESULT_PATH`, by default is `''`.
> Profiler files path configurable

- MANIFEST.in
Trailing slashes breaks compilation on Windows. This commit removes these trailing slashes.
> Remove trailing slashes in MANIFEST.in

- project/tests/test_lib/mock_suite.py
- silk/middleware.py
Heya!
I made the SilkyMiddleware compatible with the new Django 1.10 middleware and also fixed the broken tests (typo with content_type not being a field on Response).
Thanks!
Remco
> Django 1.10 compatibility

- silk/views/requests.py
> Swap imports to avoid emitting warnings

- requirements.txt
- setup.py
- silk/middleware.py
Keep trying the `_process_response` until it works. It tends to fail with big MySQL queries.
MySQLdb specifically does not manage the connections and will error if you try to reuse a stale connection. One that has closed or expired. You need to explicitly check for this error case and handle it. This PR excepts the `OperationalError` whenever the `silk` middleware has to processs a relatively large query in it's `_process_response`.
> Operational Error When Silk Is Used On Big SQL Queries

- requirements.txt
- setup.py
- silk/middleware.py
Addresses #142
Using Django’s DatabaseError class as the exception to catch keeps the
library and this try catch database platform agnostic. That way
developers who have a Postgres or MySQL backend should mutually benefit
from this retry.
> Updates exception handling to use Django DatabaseError class

- project/tests/test_compat.py
- silk/model_factory.py
I would like to fix this warning I see a lot using silk with python3.5 and django 1.9:  `Response to request with pk 97a4673c-ba72-485b-88cf-f3a35e583b7b has content type application/json but was unable to parse it`
In the `ResponseModelFactory.body(...)` method it seems to hit this exception on python3 because the `content` variable is a byte string, not because it is an invalid json string.  I have added a check to test if it is not a `str` type object, then if so decode the `bytes`.
I do not have much experience in python2/3 compatibility so a extra pair of eyes to double check would be appreciated.
> Fix for byte string incompatibility in ResponseModelFactory.body() on py3

- .travis.yml
- project/project/settings.py
Hi all, I have added some config to `.travis.yml` to allow for testing on "most" of the Django database backends. I have included PostgreSQL, MySQL and SQLite3. The only default Django backend that is missing is Oracle. This can be included however it would mean pulling in [this project](https://github.com/cbandy/travis-oracle) and also a maintainer setting up an oracle account.
The motivation for this change is issue #142 and to allow for earlier detection so that a broken release doesn't make it to PyPi.
As you can [see on Travis](https://travis-ci.org/mattjegan/silk/builds/165481576) it works well.
> Travis config to test on the different django database backends.

- silk/profiling/profiler.py
Hello!
When using MIDDLEWARE setting from Django 1.10 (instead of MIDDLEWARE_CLASSES, like [README](https://github.com/django-silk/silk/blob/85af6e2d25cf1e1be44d5de142fdfa8ec11754e5/README.md) suggests), silk keeps complaining that
```
Cannot execute silk_profile as silk is not installed correctly.
```
This PR fixes that.
> Allow using Django 1.10 MIDDLEWARE setting instead of MIDDLEWARE_CLASSES

- README.md
Django >= 1.10 : `MIDDLEWARE` is list type.
Django < 1.9 : `MIDDLEWARE_CLASSES` is tuple type.
Details here : https://docs.djangoproject.com/en/1.10/releases/1.10/#new-style-middleware
Therefore,
~~~~
MIDDLEWARE_CLASSES = (
...
'silk.middleware.SilkyMiddleware',
...
)
~~~~
would be
~~~~
MIDDLEWARE = [
...
'silk.middleware.SilkyMiddleware',
...
]
~~~~
> Update middleware setting for Django >= 1.10

- silk/collector.py
The middleware wasn't storing anything because when tried to disable python profiler and it doesn't exists (initialized with None) raise a ValueError, so that the middleware stops at this point and don't register anything.
> Fixes #161

- silk/templates/silk/profile_detail.html
- silk/templates/silk/profiling.html
- silk/views/profile_detail.py
With these changes, the profile content will appear in profile detail view, as well as a link to download the profile file. I tried to reuse CSS classes, but the aspect can be improved.
> Fixes #170

- silk/templates/silk/profile_detail.html
Hi, 
This PR adds the `text-align: left` to the pyprofile class in the profiling view. 
As shown in the above screenshot, without a text align the output is difficult to read with longer function names. 
With the `text-align` added, it is much more readable. 
Thank you for the consideration! This is an incredibly useful package for us.
> Add text-align property to pyprofile class for readability

- CONTRIBUTING.md
- README.md
Various modifications to documentation & repo to meet Jazzband guidelines (https://jazzband.co/about/guidelines).
Once merged & project is moved to Jazzband organisation, this will close #184
> Jazzband migration

- silk/models.py
> Add explicit on_delete to foreign key and one to one relationships

- silk/templates/silk/base/base.html
Profller output, in a `pre` tag, is centered, due to an inherited rule for `#query-div` in `summary.css`:
```
#query-div {
margin: auto;
width: 960px;
text-align: center;
}
```
> left align pre tag text

- README.md
- project/tests/test_models.py
- silk/config.py
- silk/migrations/0004_request_prof_file_storage.py
- silk/migrations/0005_increase_request_prof_file_length.py
- silk/models.py
- silk/storage.py
> configurable storage class

- requirements.txt
- setup.py
gprof2dot introduced a breaking change in the latest version (specifically in [this commit](https://github.com/jrfonseca/gprof2dot/commit/45342280c636dffca74cbdc3e7ac1b4438f57c1c)). As a result the test suite for silk fails.
I've pinned the version to `<2017.09.19`.
> gprof2dot had a breaking change in 2017.09.19

- project/example_app/admin.py
- project/project/settings.py
- project/tests/test_config_auth.py
- project/tests/test_config_max_body_size.py
- project/tests/test_end_points.py
- project/tests/test_silky_middleware.py
- project/tests/test_view_sql_detail.py
- silk/middleware.py
- silk/migrations/0001_initial.py
- silk/model_factory.py
- silk/profiling/profiler.py
- silk/templatetags/silk_nav.py
- silk/urls.py
Fix some deprecations to make silk compatible with django 2.0
> Fix Django 2 deprecations

- silk/collector.py
- silk/models.py
- silk/profiling/dynamic.py
- silk/profiling/profiler.py
- silk/request_filters.py
- silk/templatetags/silk_filters.py
- silk/templatetags/silk_inclusion.py
- silk/views/requests.py
- silk/views/sql_detail.py
- silk/views/summary.py
Some minor linting to make silk PEP8 compatible (ignoring line length).  Also, replacing the `unicode` keyword with `six` because `unicode` was removed in python 3.
> Lint silk directory and fix a python 3 blocker

- silk/views/summary.py
Not sure how this got past tests for the original pull request #225, but since the filter is on an annotation, the filter field must match the annotation field.
> Fix missing db_time field

- silk/code_generation/django_test_client.py
- silk/models.py
- silk/profiling/dynamic.py
- silk/profiling/profiler.py
- silk/views/profiling.py
- silk/views/requests.py
Trivial changes, without extra variables
> Return immediately

- .travis.yml
- project/example_app/urls.py
- project/project/urls.py
- project/tests/test_lib/mock_suite.py
This adds Django 2 to the list of django versions that travis will test against.  
This still requires some work to fix various problems.  Also depends on #232 and #231.
> Test django 2 in travis

- package.json
- setup.py
Resolves #187, Resolves #229. 
Proposed release notes (feel free to modify):
```
- Support for Django 2 and Python 3.6
- Support garbage collecting old profiling data
- Moved project to jazzband
- Better data visualizations (#194)
- Added ability to filter requests by http verb (#192)
- Various UI fixes
- Various bug and testing fixes
```
Commits since 1.0.0:
```
* ec11ac8 - (HEAD -> release, origin/release) Release 1.1.0 (2 minutes ago) <Albert Wang>
* abe6d84 - (origin/master, origin/HEAD, master) Switch to set method for modifying manytomany fields (24 hours ago) <Albert Wang>
* 26bbc67 - Add app_name to example app (2 weeks ago) <Albert Wang>
* aefa8a3 - Remove unneeded app_name from test project to be django 2 compatible (3 weeks ago) <Albert Wang>
* 236d2a3 - Convert tabs to spaces …
```
> Release 1.1.0

- README.md
allowing direct installation via a single `pip install` command.
Thanks to @xrmx for the suggestion
> fix alternative github tags installation url

- silk/model_factory.py
> Use force_text in ResponseModelFactory to avoid b' prefix in django 2

- silk/templates/silk/sql.html
We may want to open the links in sql details page in new tab. Please review and approve this PR.
> Opening sql queries in new tab is very useful

- silk/management/commands/silk_clear_request_log.py
Fixes #239 
This should make `./manage.py silk_clear_request_log` run a lot faster by using `TRUNCATE` for non-sqlite databases.  I believe that `objects.all().delete()` won't run `TRUNCATE` on these tables because of foreign key checks.
> Truncate tables when running silk_clear_request_log

- project/example_app/models.py
Hello,
When playing around with some changes to django-silk, I found an error in the example app.
Steps to repro:
1) Run Django server
2) Go to http://localhost:8000/admin/example_app/blind/add/ and upload a photo, and choose name.
3) Click Save
Upon saving, the following (truncated) server exception occurred:
```
....
File "/home/veer/Projects/silk/venv/lib/python3.5/site-packages/django/db/models/fields/files.py", line 86, in save
name = self.field.generate_filename(self.instance, name)
File "/home/veer/Projects/silk/venv/lib/python3.5/site-packages/django/db/models/fields/files.py", line 304, in generate_filename
dirname = datetime.datetime.now().strftime(self.upload_to)
TypeError: strftime() argument 1 must be str, not bytes
```
It seems like this is down to a simple typo in the …
> Makes example_app.models.Product.photo.upload_to a string instead of bytes

- silk/models.py
This makes sure that there will be no `IndexErrors` when calling the `garbage_collect` method.  I'm guessing this may be possible if there are fewer `Request`s than the target number of requests.
cc @avelis @drppi44 
Replaces #279
> Fix garbage collection logic for small tables

- silk/management/commands/silk_clear_request_log.py
Fix issue #290 
To not complicate the code, I removed quoting of the table name (by not passing as DB parameter which gets single quoted), as they shouldn't contain invalid characters that need escaped (non-user input), and avoids DB-specific quoting issues.
Split mysql and postgres logic to handle `TRUNCATE ... CASCADE` with postgres.  Since we're removing all silk data from the DB, this should be relatively safe unless someone created a foreign key from a custom table into a silk table (why?)
Also, added `with` around cursor for cleanup, even though the script is short-lived.
Let me know if this is an acceptable solution however!
Thanks!
Mike
> #290 Fix silk_clear_request_log errors on Postgres

- silk/templates/silk/cprofile.html
- silk/templates/silk/inclusion/request_menu.html
- silk/urls.py
- silk/views/cprofile.py
After checking multiple times, I figured out that python profile is provided only on the profile detailed page which is reachable from the profiling view only if some dynamic, decorator or context manager profile are defined. I simply created a new view allowing to get the python profile for each and every queries.
> Added a simple view in request detail context allowing to get python profile

- silk/management/commands/silk_clear_request_log.py
To be able to disable ALL triggers on a database, one needs a user that can disable system triggers.
Should fix https://github.com/jazzband/django-silk/issues/290
> Disable postgres USER triggers

- project/tests/test_config_meta.py
- project/tests/test_silky_middleware.py
- silk/middleware.py
As django-silk no longer supports django < 1.10 the MiddlewareMixin is
no longer needed.
> Modernize middleware

- project/tests/test_config_long_urls.py
- silk/models.py
MySQL index restrictions prevent us from having path or view_name be longer than 190 characters (see #38), but there is no logic in the Request object to enforce this limit when saving, so long URLs cause a 500 error.
Closes #179.
> Prevent path or view_name being longer than 190 characters

- silk/middleware.py
This is my traceback:
``` bash
python manage.py migrate
Traceback (most recent call last):
File "/home/ubuntu/webapps/smith/manage.py", line 10, in <module>
execute_from_command_line(sys.argv)
File "/home/ubuntu/venvs/agentsmith/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
utility.execute()
File "/home/ubuntu/venvs/agentsmith/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
django.setup()
File "/home/ubuntu/venvs/agentsmith/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
apps.populate(settings.INSTALLED_APPS)
File "/home/ubuntu/venvs/agentsmith/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
app_config.ready()
File …
```
> Avoid errors when doing migrate command

- silk/models.py
It would be cheaper to get a single value instead of evaluating
a full queryset.
Supersedes #304
> Make Request.garbage_collect cheaper

- project/tests/test_view_requests.py
- silk/views/requests.py
So that they are usable. We can remove the empty string path as we
already have it in the template.
While at it move all the calculation to the database for filtering
and flattening the data.
> Sort view filters values

- requirements.txt
- setup.py
- silk/views/profile_dot.py
Gprof2dot requirement was bounded because there was a breaking change in new releases.
Fixes #332
> Update gprof2dot requirement

- project/tests/test_execute_sql.py
- silk/sql.py
This is a potential fix for issue #319
> If there is no DataCollector().request then don't wrap sql queries

- README.md
- silk/config.py
- silk/profiling/profiler.py
Hello. Currently, there is no possibility to subclass the `SilkyMiddleware` and use it, because `profiling._silk_installed` always checks for `silk.middleware.SilkyMiddleware` inclusion in the middleware list. Can I suggest this option?
> SILKY_MIDDLEWARE_CLASS option

- setup.py
The project url on PyPi is outdated. 
The pull-request change the url to point to this repository.
> Fix project url on PyPi

- silk/templates/silk/base/root_base.html
So it's actually possible to use them in the filter with very
long paths.
Fix the issue for me in both chrome and firefox.
> templates: limit select width to its container one

- project/tests/test_sensitive_data_in_request.py
- silk/model_factory.py
This addresses #348. It works for me -- but being as this project has no unit testing framework I can see, :man_shrugging:
> Simplify pattern masking and handle dicts

- project/tests/test_sensitive_data_in_request.py
- silk/model_factory.py
The previous implementation does not correctly handle:
- prefixes in json
- suffixes in forms & json
- case sensitivity in forms & json
- nested values in json
These changes should fix the above issues.
> Fix hiding of sensitive data in requests

- silk/management/commands/silk_clear_request_log.py
- silk/utils/data_deletion.py
- silk/views/clear_db.py
> Clear DB page doesn't work with PostgreSQL and SQLite

- project/tests/test_view_sql_detail.py
There is a small typo in project/tests/test_view_sql_detail.py.
Should read `traceback` rather than `tracebackk`.
> docs: Fix simple typo, tracebackk -> traceback

- silk/model_factory.py
If credentials ends with `\` (for example: `--password=123456\`) re.sub() fails with error `bad escape (end of pattern)`.
> Wrap re.sub() in try-except

- project/tests/test_sensitive_data_in_request.py
- silk/model_factory.py
This fixes https://github.com/jazzband/django-silk/issues/410
This also fixes a DoS attack:
* Form is submitted with multiple empty fields that match the mask filter
* Substitution loop repeatedly calls `re.sub` with an empty pattern
* Cleansed string is inserted between every pair of characters
* Loop iterations causes exponential growth of body string, preventing the request from ever finishing
> Replace the call to re.findall with re.sub in _mask_credentials so matched values are not treated as regex patterns

- project/tests/test_sensitive_data_in_request.py
- silk/model_factory.py
Additionally, enhance tests to verify that the keys are not mangled
> Capture entire key name during cleansing in _mask_credentials

- silk/utils/data_deletion.py
resolve```django.db.utils.ProgrammingError: relation "silk_profile" does not exist```
> Clear DB error when configuring silk to use a non-' default' database

- silk/model_factory.py
The result of base64.b64encode can be ASCII decoded.
> Fix force_text RemovedInDjango40Warning

- silk/sql.py
- tox.ini
Fixes #431 and makes django-silk compatible with Django 3.1 (released today).
> Make compatible with Django 3.1

- .travis.yml
#433 added Django 3.1 to the tox matrix. The test matrix for TravisCI is held in a separate file and so also needs updating. 👍
> Added Django 3.1 to Travis test matrix

- project/tests/test_silky_middleware.py
- project/tests/urlconf_without_silk.py
- silk/middleware.py
Hi,
Right now `SilkyMiddleware` raises `NoReverseMatch` when `silk.urls` are not included in the app. There are various reasons when one _might not_ want to enable the Silk UI, but still keep the middleware around. For example, to disable Silk in production, the easiest way would be to set `SILKY_INTERCEPT_PERCENT` to 0, and not include the URLs. Unless there's a reason to keep the exception in place, I'd like to have Silk handle this gracefully.
This is my first time posting here, so I'm not too familiar with the development process. Happy to address any feedback.
Thanks
> Do not crash when silk app is not included in urls

- silk/config.py
- silk/model_factory.py
- silk/utils/data_deletion.py
Support for users to configure the ```SILKY_JSON_ENSURE_ASCII``` parameter to implement ```json.dumps``` support Chinese
> Add the SILKY_JSON_ENSURE_ASCII configuration item to support Chinese

- project/project/settings.py
- project/tests/test_view_clear_db.py
- silk/views/clear_db.py
For mysql, if `ATOMIC_REQUESTS` was enabled, `truncate` will cause an error saying `SAVEPOINT does not exist`.
So we should exempt transaction for clear_db view.
> Fix transaction error for mysql

- project/tests/test_models.py
- silk/models.py
This PR modifies the `num_joins` logic, instead of counting the occurences of the string `join` it parses the query in order to exclude all the tokens that are not SQL Keyword such as column Identifiers or String Literals.
This can be useful in order to avoid false positives
> parse query when counting joins

- tox.ini
https://github.com/psycopg/psycopg2/issues/1293
> Temporary fix for testing Django 2.2

- README.md
The current instructions in the readme regarding alternative installation methods states to use `pip install -e git+https://github.com/jazzband/django-silk.git#egg=silk`. However, this is incorrect and will result in the following error:
```bash
Obtaining silk from git+https://github.com/jazzband/django-silk.git#egg=silk
Cloning https://github.com/jazzband/django-silk.git to c:\users\username\repositories\conreq\.venv\src\silk
Running command git clone -q https://github.com/jazzband/django-silk.git 'c:\users\username\repositories\conreq\.venv\src\silk'
WARNING: Generating metadata for package silk produced metadata for project name django-silk. Fix your #egg=silk fragments.
WARNING: Discarding git+https://github.com/jazzband/django-silk.git#egg=silk. Requested django-silk from …
```
> Fix egg metadata error

- silk/views/summary.py
This PR ensures that the result in the "Most Database Queries" is actually sorted in descending order. The previous code could result in the results being out of order since the ordering was applied seperately per view_name.
> Ensure sorting between most db queries requests

- silk/views/summary.py
This PR aims to fix a bug where this summary could return a list of empty timing values if there are null values in the `time_taken` field.
> Don't return null values when computing "Most Time Overall" summary

- silk/views/summary.py
This PR aims to fix a bug where this summary could return a list of empty timing values if there are null values in the queries__time_taken field.
>  Don't return null values when computing "Most Time Overall" summary

- project/tests/factories.py
- project/tests/test_db.py
- silk/sql.py
The project's existing tests all seem to mock DB access, unless I'm missing something. This PR adds some simple tests that actually access the DB. This allows us to actually catch compatibility errors like those in #489 ,
Let me know what you think.
> Add tests that access the actual DB

- project/tests/test_app_config.py
- project/tests/test_models.py
- silk/__init__.py
- silk/apps.py
This is to avoid unnecessary migrations caused by default "id" field type change from `AutoField` -> `BigAutoField` in Django 3.2.
new test added
- testing if proper AppConfig class is loaded by Django
- testing if package has no pending migrations and will not generate new migrations when running `makemigrations` on user-end.
> `apps.py` added with `default_auto_field` set

- README.md
- project/tests/test_sensitive_data_in_request.py
- silk/config.py
- silk/model_factory.py
Currently the masking logic has hard coded set of sensitive keys under RequestModelFactory to mask the body value. There are times where I need to add values into the existing keys. It is hard with the current implementation.
Since the masking logic is already implemented, it would be nice to have the sensitive keys configurable from Django settings. This will make the masking more flexible for many users.
For this I create a new key in config
`SILKY_SENSITIVE_KEYS `
with default value
`{'username', 'api', 'token', 'key', 'secret', 'password', 'signature'}`
so it does not affect any previous users.
Let me know if this is a good addition
> Make sensitive keys set configurable

- project/tests/test_dynamic_profiling.py
- project/tests/test_lib/assertion.py
- project/tests/test_view_profiling.py
- project/tests/test_view_requests.py
Fixes #515 
`assertDictContainsSubset` has been deprecated since python 3.2 and removed in 3.11. 
https://docs.python.org/3.11/whatsnew/3.11.html
> Replace assertDictContainsSubset

- project/tests/test_execute_sql.py
- silk/sql.py
SQLCompiler has a `.connection` instance which is already aware of what
database it should use. As such, when running EXPLAIN query let's use
that connection instead of connection to a default database.
Fixes #522.
I will add unit tests early next week.
> Use correct db in a multi db setup

- requirements.txt
Packages shouldn't need to be duplicated between setup.py (dependencies for users of django-silk) and requirements.txt (dependencies for developers of django-silk).
This is a first step to pinning dependencies in `requirements.txt` as suggested in #548.
> Remove duplicate requirements.txt dependencies

- README.md
- project/tests/test_db.py
- silk/config.py
- silk/sql.py
Adding support for additional flags that can be passed as part of the "analyze" query, for more explicit analysis.
> Fixing #530 - Adding support for SILKY_EXPLAIN_FLAGS

- silk/templates/silk/base/root_base.html
- silk/templates/silk/requests.html
I'm using you're package quite often and wanted to give something back to this project 😄 
This PR focuses on improving experience on _Request_ tab - one improvement per commit:
*  Add message when there are no requests to display: when there are no matches instead of displaying an empty page, let user know that there are no filter results
* Add 'Clear all filters' button - when user fills in a few filters, clearing them is rather tedious task so I thought it would be nice to have a button to clear filters.
*  Add small margin for filter selects: I think this change makes filter section looks much better.
This branch is based off 4.2.0 tag, please let me know if I need to rebase.
> Quality of life improvements in Requests tab

- .pre-commit-config.yaml
I was getting this error when creating #561:
```
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
I believe switching from `git://` to https://` should solve this problem and align this particular repository URL with all the other ones.
> Fix pre-commit-config

- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.md
- docs/index.rst
- setup.py
- silk/__init__.py
- tox.ini
Depends on https://github.com/jazzband/django-silk/pull/566
> Drop support for Django 2.2 (EOL)

- CHANGELOG.md
- package.json
This is backwards incompatible because it drops support for Django 2.  django-silk v4.4.0 will be the last version to support Django 2.  django-silk v5.0.0 will support Django 3+ only.
> Release version v5.0.0

- docs/index.rst
- silk/profiling/dynamic.py
There are small typos in:
- docs/index.rst
- silk/profiling/dynamic.py
Fixes:
- Should read `instinct` rather than `instict`.
- Should read `arbitrary` rather than `arbritary`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- project/tests/test_collector.py
- project/tests/util.py
- silk/collector.py
This PR fixes https://github.com/jazzband/django-silk/issues/208
> Add support for storages, that don't implement full filesystem path

- silk/collector.py
- silk/middleware.py
- silk/model_factory.py
Decrease unnecessary database hits as mentioned in #587
> Decrease unnecessary database hits (#587)

- project/tests/test_profile_parser.py
- requirements.txt
Since the project no longer declares a requirement of contextlib2, and
the lowest version of Python supported is 3.7, we should remove the use
of contextlib2. Switch the import to contextlib.
> Use contextlib in test_profile_parser

- project/tests/test_filters.py
- project/tests/test_models.py
- setup.py
Following up on #581, remove the `pytz` package which was only being used in tests to load the UTC offset which by definition is always 0.  `django.utils.timezone.utc` (as well as `datetime.timezone.utc`) both suffice and are already available to be imported in django-silk.
Fixes #581
> Remove unneeded pytz package

- .github/workflows/test.yml
- README.md
- setup.py
- tox.ini
Adds Python 3.11 to GHA test workflow job matrix, tox, and trove classifers. Updates the README to add 3.11 to list of Python versions `django-silk` has been tested against.
Also removes the `<2.9` version restriction from the `psycopg2-binary` dependency in the Postgres tox env, as that was seemingly added as a temporary fix for Django 2.2 (#486), which this package no longer supports.
> Add Python 3.11 to CI, tox, and trove classifiers

- .github/workflows/test.yml
Adds `postgres-version` and `mariadb-version` to CI job matrix and restricts `django-version` to running the lowest supported DB version for that release of Django.
Django development supports Postgres >12 and MariaDB >10.4, so in CI those two tox envs were failing across all Python versions:
```shell
___________________________________ summary ____________________________________
py310-djmain-sqlite3: commands succeeded
py310-djmain-mysql: ignored failed command
py310-djmain-postgresql: ignored failed command
congratulations :)
```
[https://docs.djangoproject.com/en/dev/ref/databases/#postgresql-notes]()
[https://docs.djangoproject.com/en/dev/ref/databases/#mariadb-notes]()
> Switch Django dev in CI to Postgres 12 and MariaDB 10.4

- project/tests/test_view_requests.py
- silk/templates/silk/base/root_base.html
- silk/views/requests.py
Two enhancements in this PR:
- the `'show', 'order_by', 'order_dir', 'view_style'` params are retained so when you click on the "Requests" menu item, you keep these (they won't be reset when "Clear all filters" is clicked as they are not filters)
- a invisible submit button was added to filter form so that when you set a value and press enter, the form is submitted
I will open a cleanup issue, as I find the filters form heavily relying on JavaScript, and it should not be IMHO.
> #46 Retain ordering, view style and limit

- project/tests/test_end_points.py
- setup.py
- silk/code_generation/curl.py
- silk/code_generation/django_test_client.py
> #625 Drop dependency to jinja2

- .github/workflows/test.yml
According to https://docs.djangoproject.com/en/4.1/faq/install/, django versions >= 4.0 do not support python 3.7 anymore and django versions <= 4.0 do not support python 3.11.  This PR excludes those 5 combinations of python and django versions from being tested.  Also, the tests for those 5 combinations of django and python are failing.
> Prune test matrix of unsupported python/django combinations

- project/example_app/admin.py
- project/tests/urlconf_without_silk.py
Debugging the failures in #620 , I ran django-upgrade manually to find what it was doing to files to cause the tests to fail.  This PR contains the changes from running django-upgrade manually (and matches #620) except for the below change from django-upgrade which breaks tests and therefore is not included in this PR:
```diff
diff --git a/silk/model_factory.py b/silk/model_factory.py
index ba21fed..9a091c0 100644
--- a/silk/model_factory.py
+++ b/silk/model_factory.py
@@ -74,7 +74,7 @@ class RequestModelFactory:
self.request = request
def content_type(self):
-        content_type = self.request.META.get('CONTENT_TYPE', '')
+        content_type = self.request.headers.get('content-type', '')
return _parse_content_type(content_type)
def encoded_headers(self):
```
After this PR is landed, …
> Run django-upgrade manually

- silk/model_factory.py
Based on the comment https://github.com/jazzband/django-silk/pull/641#pullrequestreview-1245196140, there's not a good reason to have these lines that attempt to strip `content_type`.  
If `strip()` is a method on a string, `strip()` will return a string making the `strip()` a few lines below superfluous (`s.strip().strip() == s.strip()`).  If `strip()` does trigger the try/catch, the try/catch will be ineffective anyways because the later `strip()` will also trigger an `AttributeError`.  There is a possibility that a different type implements `strip()` in a way that multiple strips have different behavior, but it doesn't seem possible given how the `_parse_content_type` function is called.
> Remove unneeded content_type strip

- project/tests/test_compat.py
- project/tests/test_config_long_urls.py
- project/tests/test_config_max_body_size.py
- project/tests/test_encoding.py
- project/tests/test_multipart_forms.py
- project/tests/test_sensitive_data_in_request.py
- silk/code_generation/curl.py
- silk/model_factory.py
As recommended by https://github.com/adamchainz/django-upgrade#httprequestheaders, switch from `request.META` to `request.headers`.  This slightly simplifies several test cases by not having to convert between META and headers (see https://docs.djangoproject.com/en/dev/ref/request-response/#httprequest-objects for more information).  However, headers are case insensitive which introduces some case-changes.  
All of the changes in this PR are limited to tests, except for a very minor change when generating curls.
This is a followup to https://github.com/jazzband/django-silk/pull/640#issuecomment-1375269162
> Switch from request META to request headers

- project/tests/test_compat.py
- silk/model_factory.py
django-silk doesn't support django<3.2 anymore.  Therefore, the `_get_response_headers` function that provides compatibility with django<3.2 isn't needed.
> Remove support for looking up headers on django <3.2

- README.md
- project/tests/test_collector.py
- silk/collector.py
- silk/config.py
The aim of this pull request is to generate a more informative profile file name. This would allow us to identify the endpoint that generates a profile file without the need to open it.
To avoid breaking any existent use case I set this behavior behind the setting `SILKY_PYTHON_PROFILER_EXTENDED_FILE_NAME` that by default is disabled.
If you think we can change the generated filename without worry we can simply apply this change always without the need to introduce the new settings.
> Allow to generate more informative profile file name

- silk/templates/silk/base/base.html
- silk/templates/silk/clear_db.html
- silk/templates/silk/cprofile.html
- silk/templates/silk/profile_detail.html
- silk/templates/silk/profiling.html
- silk/templates/silk/request.html
- silk/templates/silk/requests.html
- silk/templates/silk/sql.html
- silk/templates/silk/sql_detail.html
- silk/templates/silk/summary.html
Add a "pagetitle" block to Silky templates so that when multiple Silky browser tabs are open, it's easier to tell which is which.
> Add a "pagetitle" block to Silky templates

- project/tests/test_sensitive_data_in_request.py
- silk/model_factory.py
> Handle case-insensitive sensitive headers

- project/tests/test_filters.py
- project/tests/test_models.py
`django.utils.timezone.utc` is deprecated and should be replaced with `datetime.timezone.utc` which exists in all versions of python supported by django-silk.
> Remove deprecated django.utils.timezone.utc

- project/tests/test_view_clear_db.py
- silk/config.py
- silk/templates/silk/clear_db.html
- silk/views/clear_db.py
Added a new config option that will allow user to clear profiler profiles from storage when Clear DB is called. This is helpful functionality especially in development environment where frequent DB cleaning is done.
> Allow option to delete profiles

- README.md
- silk/models.py
This PR should fix the deprecation warning for `get_storage_class` by trying to import and use the `storages` class instead.  However, the latter is not an exact replacement for the former, requiring a different configuration option to be provided under the `STORAGE` instead of the `SILKY_STORAGE_CLASS` setting.  This makes this PR a forwards incompatible change requiring a minor semver bump.
Fixes #656
> Fix deprecation warning for get_storage_class

- project/tests/test_collector.py
- silk/collector.py
> Gracefully error out when there are concurrent profilers

- silk/__init__.py
This removes the dependency on setuptools, which is no longer automatically installed in virtual environments starting in Python 3.12.
> Derive version from importlib

- README.md
Based on the comment from [#692 ](https://github.com/jazzband/django-silk/pull/692#issuecomment-1888069319)
> Add a readme note about profiler behavior changes after python 3.12

- project/tests/test_execute_sql.py
- silk/collector.py
As a followup to #692 , this diff cleans up two places where cProfile is enabled but not disabled.  
In `collector.py`, the `DataCollector()._configure()` logic is changed so that the profiler is explicitly stopped before the profiler is set to `None`.  If the profile is set to `None`, future profiles are blocked even though the old profiler is not accessible and pending garbage collection.
In `test_execute_sql.py`, the test cases are enabling profiling through `DataCollector` but the test cases are not explicitly disabling profiling when finished.  This causes other test cases to fail when they attempt to profile.  (I'm not sure why these test cases explicitly require disabling profiling even though many other test cases also initialize `DataCollector` and enable profiling)
#692 should …
> Always disable cProfile as part of cleanup

- .github/workflows/test.yml
- README.md
- docs/index.rst
- project/tests/test_execute_sql.py
- setup.py
- silk/collector.py
- tox.ini
Depends on #669 
Depends on #685 
Depends on #687 
Depends on #692 
Depends on #699
> Support and Test Against Django 5

- .github/workflows/test.yml
- README.md
- docs/index.rst
- setup.py
- tox.ini
Test against up-to-date supported versions of Django, Postgres, and MariaDB.
> Update test matrix

- project/tests/test_collector.py
`_get_prof_file_name` did not work correctly when the file separator was not `/`.
> Fix test failures on Windows

- project/tests/test_code_gen_curl.py
- project/tests/test_code_gen_django.py
- silk/code_generation/curl.py
- silk/code_generation/django_test_client.py
These code fragments are escaped when they are substituted into the `silk/request.html` template, so they should not be escaped an extra time when they are constructed.
Fixes #688.
> Fix double-escaping of the curl and Python example code

- project/tests/test_models.py
- silk/models.py
This pull request addresses the issue where the `tables_involved` property of the SQLQuery model fails to recognize tables involved in UPDATE operation. The current implementation only captures tables involved in SELECT and JOIN operations.
The updated implementation includes UPDATE operation to ensure comprehensive table identification. The modified code is as follows:
```python
class SQLQuery(models.Model):
query = TextField()
...
@property
def tables_involved(self):
...
for idx, component in enumerate(components):
...
if (
component.lower() == "from"
or component.lower() == "join"
or component.lower() == "as"
or component.lower() == "update"
):
...
return tables
```
By including update statement, this change ensures that all relevant tables are captured for a more complete SQL query …
> Enhance tables_involved Property to Include Tables from Update and Delete Operations

- project/tests/test_silky_middleware.py
- project/tests/test_view_profiling.py
- project/tests/test_view_requests.py
- project/tests/test_view_summary_view.py
- silk/middleware.py
- silk/request_filters.py
- silk/views/profiling.py
- silk/views/requests.py
- silk/views/summary.py
Hello!
In this PR I try fix the issue https://github.com/jazzband/django-silk/issues/347
Doesn't fail when one of these middlewares are not present:
```
'django.contrib.sessions.middleware.SessionMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware'
```
and if `SILKY_AUTHENTICATION` is `True`, an exception is raised: **SILKY_AUTHENTICATION can not be enabled without Session, Authentication or Message Django's middlewares**
Let me know any change required!
Thank you!
> Fix when Session, Authentication or Message middlewares are not present

- silk/models.py
> Annotate time_taken fields as milliseconds rather than seconds

- .gitignore
- Vagrantfile
I don't think anybody uses this Vagrantfile which depends on a 12 year old version of Ubuntu.  There are no references to it in documentation or code.
> Remove old vagrantfile

- project/tests/test_models.py
- silk/models.py
This will fix a "FIXME" in the tests, and will make the code faster by utilizing db aggregation instead of python sum
>  Refactor SQL query time calculation to use Django aggregation

- silk/templates/silk/profiling.html
- silk/templates/silk/requests.html
Fixes #115 
Corrected the units from seconds to milliseconds.
> Correct units in profiling.html and requests.html

- .github/workflows/test.yml
- project/tests/test_view_requests.py
- tox.ini
> Test against Django 5.1

- README.md
- docs/index.rst
- setup.py
#732 started testing against Django 5.1.
Django-silk can now officially declare Django 5.1 as supported.
For #730
> Officially declare support for Django 5.1

- CHANGELOG.md
- package.json
cc @mgaligniana @emregeldegul @SpecLad @ka28kumar @beltagymohamed 
Depends on #734 
Fixes #731
> Release version 5.2.0

- .github/workflows/test.yml
- tox.ini
Django 3.2 is end-of-life.  Remove testing against Django 3.2.
For #727
> Remove tests against Django 3.2

- .github/workflows/test.yml
- .pre-commit-config.yaml
- tox.ini
To be rebased on top of #728 
Since Django 3.2 won't be supported anymore, have [django-upgrade](https://github.com/adamchainz/django-upgrade) target Django 4.2 instead.
For #727
> Set django-upgrade to target Django 4.2

- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.md
- docs/index.rst
- project/project/settings.py
- project/tests/test_view_requests.py
- setup.py
- silk/models.py
- tox.ini
Depends on #728  , #729 
Fixes #727 
This PR removes all code related to Django 3.2.  Note that this breaks support for Django 3.2.
> Remove Django 3.2 support

- .github/workflows/test.yml
This updates the versions of databases that are used for testing django-silk
- Update postgres to the oldest and newest supported versions of postgres
- Update mariadb to the supported LTS versions (except for 10.5)
> Update test postgres and mariadb versions

- silk/middleware.py
This PR rewrites the retry logic in `process_response` to not use `break` in `finally` (#745) and to put an explicit cap of 2 attempts to process a response before letting the request continue on through the middleware.
The original code also implicitly had a cap of 2 attempts because `finally: break` would have executed regardless of if `_process_response` succeeded which meant there would always be either 1 attempt (`try`) or 2 attempts (`try` and `except`), never any more.  The original likely meant to have `else: break` to retry forever, but retrying forever is likely undesirable in this situation.
Follows up on #140 
Fixes #745
> Fix swallowing exceptions and explicitly cap retries in process_response

- README.md
- docs/troubleshooting.rst
> doc: Adds updated documentation on middleware ordering, issue #302

- requirements.txt
This updates networkx to v3.2.1.  It resolves a backwards incompatibility from v2.6.3 where optional requirements stopped being required in networkx.  Adding pillow as a dependency resolves this issue and fixes tests.
> Update networkx to v3.2.1

- silk/middleware.py
Change Logger `warn` to `warning` due to deprecation.
> fix: update Logger warn to warning in middleware file

- silk/views/request_detail.py
I am frequently facing timeout because of request with very large body,
These are caused by body processing in request details to generate curl and client commands that are not so essential in most cases (in particular when working with large request)
> Avoid timeout caused by Request with large body

- silk/model_factory.py
Python 3.6+ (all versions of python supported by django-silk) can run `json.loads` on strings or bytes according to https://docs.python.org/3/library/json.html#json.loads
There is therefore no reason to decode bytes to strings before passing to `json.loads`
> Skip converting bytes to string before json loading

- setup.py
- silk/code_generation/django_test_client.py
- tox.ini
Fixes #780 
Mark autopep8 as an optional dependency.  If the dependency is available, use it, otherwise return the code as is.
> Make autopep8 optional

- .github/workflows/test.yml
- README.md
- docs/index.rst
- setup.py
- tox.ini
Django 5.0 dropped security support on April 2, 2025 making it EOL.
This PR drops django-silk support for Django 5.0.
> Drop support for Django 5.0

- silk/model_factory.py
From https://docs.python.org/3/library/logging.html#logging.Logger.warning:
```
Note There is an obsolete method warn which is functionally identical to warning. As warn is deprecated, please do not use it - use warning instead.
```
Basically the same as #766
> Replace deprecated logger.warn with logger.warning

- README.md
- docs/quickstart.rst
The egg for django-silk should be `django_silk`, not `silk` (which hasn't been the name of this package in years) nor `django-silk`, which [pip will stop converting to django_silk soon](https://github.com/pypa/pip/pull/11617).
> Fix egg name in documentation

- silk/views/request_detail.py
This was a regression from https://github.com/jazzband/django-silk/commit/0a84caaec72ea5ff7739599a64467b1867cd2f2a / https://github.com/jazzband/django-silk/pull/768
This PR fixes a bug where the Curl and Django Test Client code sections were empty. The reason for the bug was that the variables were tuples instead of strings. When the template is rendered, the `curl.strip` method is called which expected a string.
The result of this change is the following:
Prior to the change:
> fix: curl/client values not rendering in request_detail

- project/tests/test_silky_middleware.py
- silk/middleware.py
I believe there is a race condition when adding/removing the `execute_sql` wrapper in multi-threaded environments which was added in #798 as a way for silk to clean up after itself.  This fully reverts #798 (other parts of it were reverted in #807) to remove the race condition.
Fixes #811 
Reverts #798
> Fix middleware cleanup race condition
