silk/middleware.py
This pull request aim to fix a problem where the timing for processing the request information was not taken in account in the meta-timing. 
The save was done in a meta-timing context.
=> Fixed report handling timing not included in meta-timing

project/tests/test_view_requests.py, silk/views/requests.py
This closes #96 
oops, you're right, i forgot about testing
=> Refactor Unit Tests to test new sort ordering structure.

requirements.txt
* Uprevving pillow so that we can successfully `pip install -r requirements.txt` when building this. 
* Version 3.2 was failing, `pip install pillow` without specifying a version was pulling version 3.3 and installing successfully.
Trace:
```
Running setup.py install for Pillow ... error
Complete output from command /usr/bin/python27 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5IFQZ1/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-g3oKlu-record/install-record.txt --single-version-externally-managed --compile:
Single threaded build, not installing mp_compile:1 processes
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating …
```
=> update pillow requirement so installation succeeds

silk/collector.py
https://github.com/django-silk/silk/issues/153
cProfiler now located within thread local storage.
=> Bugfix for issue #153

setup.cfg, setup.py
that should be OK for now as far I know.
@avelis
=> Wheel support

README.md
In order to have a nicely formatted display like that shown in the screenshots collect static needs to be run to pull in js/css assets.
=> Mention collectstatic

silk/profiling/profiler.py
The 'warn' method is deprecated, use 'warning' instead
=> Deprecation: update to warning

project/tests/test_filters.py, silk/request_filters.py, silk/templates/silk/requests.html, silk/views/requests.py
I added a new user interface element to filter the requests based on http status code.
=> Added status code filter

silk/static/silk/lib/sortable.js, silk/templates/silk/sql.html
Use sortable.js to make the sql queries table sortable on the queries page.
=> Sortable sql table

setup.py
This is required for graph visualization
=> Add missing gprof2dot to setup.py

silk/models.py
=> Allow prof_file to be blank, not null

README.md
Reviewed the README to remove typos and the use of contractions.
=> Removed typo errors and fixed contractions

README.md
Just pulled a basic config from `.travis.yml`. Sorry if this was already documented somewhere, I couldn't find it!
=> Add extra documentation covering environment variables and running tests

docs/quickstart.rst, docs/troubleshooting.rst
This should be the last few links that pointed to the old mtford90 repository.
Helps with finishing up https://github.com/jazzband/roadies/issues/67
=> Fix github silk links to point to jazzband

project/tests/test_filters.py
Should fix some of our broken builds.
=> Fix flaky test by rounding off floats

project/tests/test_config_auth.py, project/tests/test_migrations.sh, project/wsgi.py, silk/model_factory.py
=> Remove django 1.6 references

silk/templates/silk/sql.html
Function should be declared in <script> tag
=> function declaration fix

package.json, setup.py
=> Release 2.0.0

silk/templates/silk/sql.html
This reverts commit 6b0b22e48dd772e46d23e68efb95cc08935270f5.
Fixes #271
=> Revert "Opening sql queries in new tab is very useful"

package.json, setup.py
https://github.com/jazzband/django-silk/releases/tag/untagged-4df170e6f182a1c1bbf1
Fixes #282
=> Release 3.0.0

README.md, package.json
The links currently 404 and I haven't seen anybody request to use it.
=> Remove gitter links

README.md
I added a note in the README to disclose [this security issue](https://github.com/jazzband/django-silk/issues/305).
=> Disclose security issues

project/project/urls.py, project/tests/test_sensitive_data_in_request.py, silk/model_factory.py
Potential fix for the issue https://github.com/jazzband/django-silk/issues/305
=> Mask sensitive data

.gitignore, .travis.yml, README.md, docs/index.rst, project/gen.py, project/manage.py, project/wsgi.py, setup.py
The goal of this PR is to add Django 2.2 to the test matrix.
=> Add testing support for django 2.2

.travis.yml, Dockerfile, docker/docker-compose.yml, project/run_tests.sh
This adds a docker setup to the project. It's easier for me to just setup a dockerfile than to get my host setup right :)
=> Add docker setup

CHANGELOG.md, package.json, setup.py
=> Updated version to 3.0.4

project/tests/test_sensitive_data_in_request.py, silk/model_factory.py
Mask values in Authorization headers
Fixes # #375
=> Mask authorization header

.travis.yml, README.md, docs/index.rst, requirements.txt, setup.py
- Removed django<2.2 support
- Added django 3.0
connects #384
=> Removed django<2.2 support and added django 3.0 support

.travis.yml, README.md, docs/index.rst, project/test-requirements.txt
Added python3.8 in docs and travis
=> Added Python 3.8 support

CHANGELOG.md, package.json, setup.py
connects https://github.com/jazzband/django-silk/issues/384
=> Release 4.0.0

README.md, silk/collector.py, silk/config.py
=> Add function support for enabling profiling

CHANGELOG.md, package.json
=> Release 4.0.1

silk/model_factory.py
This is a fallback functionality to accessing and parsing the raw
request body, if the body exceeds DATA_UPLOAD_MAX_MEMORY_SIZE.
The access to self.request.body is aborted by django on too large
requests, so instead of failing the request, we set raw_body to a fixed
warning string and attempt to get the parsed request data from
self.request.POST and .FILES into body.
X-Signed-off-by: Georg Lukas <georg@op-co.de>
=> RequestModelFactory: fallback if request body too large, fix #162

.travis.yml, project/tests/test_encoding.py, silk/models.py, silk/templatetags/silk_filters.py, silk/views/sql_detail.py
=> Add Python 3.9 compatibility

.github/workflows/test.yml, README.md, setup.py, tox.ini
Hi, it's my first pull requests 😄 I'm trying to resolve #543
=> Update django version

project/tests/test_silky_profiler.py
=> Some tests misusing assertTrue for comparisons fix

.pre-commit-config.yaml, project/project/urls.py
https://github.com/adamchainz/django-upgrade
=> Add django-upgrade to pre-commit hooks

CHANGELOG.md, package.json
=> Release version v4.4.0

CHANGELOG.md, package.json
Releases #574 backported to v4
=> Release v4.4.1

CHANGELOG.md, package.json
Contains #592 , #588 , #603 , #590 , #596
=> Release version v5.0.2

requirements.txt, setup.py
Two package dependencies and two test dependencies seem to be unneeded.  Removing them from setup.py and requirements.txt as cleanup.
=> Prune unneeded dependencies

silk/profiling/profiler.py, silk/templates/silk/profiling.html
=> #269 Better check whether app is installed

CHANGELOG.md, package.json
Fixes #622 
After merging,
```
git tag 5.0.3
git push --tags
```
=> Release version v5.0.3

CHANGELOG.md, package.json
Depends on #692 
Depends on #686 
Depends on #693
=> Release version 5.1.0

.github/workflows/test.yml, project/tests/test_view_requests.py, requirements.txt, tox.ini
=> Update python dependencies

CHANGELOG.md, package.json
=> Release 5.2.1

CHANGELOG.md, package.json
Releases #754 and #753 
cc @Tatsh
=> Release 5.3.1

CHANGELOG.md, package.json
Fixes #762 
including #757 (@tatsh) and #758 (@SoyJoseC)
=> Release 5.3.2

README.md, docs/quickstart.rst
As a followup to #782 , make the formatting dependency updates more visible.
=> Add documentation for extra formatting dependencies

CHANGELOG.md, package.json
Depends on #802 
Depends on #801 
Depends on #798
=> Release 5.4.1

project/tests/test_execute_sql.py, silk/sql.py
This partially reverts #798 in commit e00b93c8bc6c8cdd3ca12be99b2b00e7f89f5145.  It keeps the middleware cleanup of `execute_sql` in place (not reverted).
Fixes #806
=> Revert #798.  Fix compatibility with JSONField

project/tests/test_execute_sql.py, silk/sql.py
An alternative approach to #808
=> Catch sql encoding errors
